---
# refrence https://itsfoss.com/disable-ipv6-ubuntu-linux/
- name: P-1 PushKeys to Linux Servers
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - ./vars/vars.yml
  gather_facts: yes
  tags:
    - push_keys
    - linux

  tasks:
    - name: P-1_T-1 Push SSH Keys to Nodes
      ansible.posix.authorized_key:
        user: "{{ user_var }}"
        state: "{{ st8 }}"
        key: "{{ lookup('file', './james-pubkey/id_ed25519.pub') }}"
      tags: 
          - push_keys
          - linux

- name: P-2 "Create Turing Group"
  hosts: all
  become: yes
  vars_files:
    - ./vars/vars.yml
  tags:
    - turing
    - linux

  tasks:
    - name: P-2_T-1 "Ensure turing group exists"
      ansible.builtin.group:
        name: "{{ grp_name_var }}"
        state: "{{ st8 }}"
      tags:
        - turing
        - linux

    - name: P-2_T-1 Remove Sudoers File for group if it exists
      ansible.builtin.file:
        dest: /etc/sudoers.d/{{ sudoers_file_var }}
        state: "{{ st8 }}"
      tags:
        - no_turing
        - linux

    - name: P-2_T-2 "Add Sudoers.d/turing file"
      copy:
        dest: /etc/sudoers.d/{{ sudoers_file_var }}
        content: "%turing ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'
      tags:
        - turing
        - linux
        - sudoers

- name: P-3 Create User
  hosts: all
  become: yes
  vars: 
    # u-name: user
    # st8: present
    sudo_group_map:
      RedHat: "wheel"
      Debian: "sudo"
      Suse: "wheel"
  vars_files:
    - ./vars/vars.yml
    - ./vars/vault.yml

  tags:
    - create-user
    - linux

  tasks:
    - name: P-3_T-1 "Ensure user exists"
      ansible.builtin.user:
        name: '{{ u_name }}'
        shell: /bin/bash
        state: '{{ st8 }}'
        home: /home/{{ u_name }}
        create_home: yes 
      tags:
        - create-user
        - linux

    - name: P-3_T-1A Add user to group for Sudo access
      ansible.builtin.user:
        name: '{{ u_name }}'
        groups: '{{ sudo_group_map[ansible_os_family] }}'
        append: yes
      tags:
        - create-user
        - linux

    - name: P-3_T-2 "Set password for user"
      ansible.builtin.user:
        name: '{{ u_name }}'
        password: "{{ password_var | password_hash('sha512') }}"
      tags:
        - create-user
        - linux

    - name: P-3_T-3 "Ensure user has .ssh directory"
      file: 
        directory": /home/{{ u_name }}/.ssh
        state: directory
        owner: '{{ u_name }}'
        group: '{{ u_name }}'
        mode: '0700'
      tags:
        - create-user
        - linux

    - name: P-3_T-4 "Check to see if the User has Keys if not then create them"
      become_user: '{{ u_name }}'
      comunity.crypto.openssh_keypair:
      path: /home/{{ u_name }}/.ssh/id_ed25519
      type: ed25519
      size: 4096
      mode: '0600'
      when: not lookup('file', '/home/' + u_name + '/.ssh/id_ed25519', errors='ignore')
      tags:
        - create-user
        - linux

- name: P-4 Add User to Turing Group
  hosts: all
  become: yes
  vars_files:
    - ./vars/vars.yml
    - ./vars/vault.yml
  vars: 
    # u-name: user
    # st8: present
  tags:
    - turing-user
    - linux

  tasks:
    - name: P-4_T-1 "Ensure user is in turing group"
      user:
        name: '{{ u_name }}'
        groups: turing
        append: yes
        state: '{{ st8 }}'
      tags:
        - turing-user
        - linux

- name: P-5 Install Linux Packages
  hosts: all
  become: yes
  vars:
    # st8: present
    # package_list:
    #   - git
    #   - vim
    #   - curl
    #   - wget
    #   - net-tools
    #   - htop
  tags:
    - linux-packages
    - linux

  tasks:
    - name: P-5_T-1 "Install Linux Packages"
      ansible.builtin.package:
        name: "{{ package_list }}"
        state: "{{ st8 }}"
      tags:
        - linux-packages
        - linux

- name: P-6 Patching and updating
  hosts: all
  become: yes # Needed for package management
  gather_facts: yes # Needed to use ansible_os_family
  tags:
    - patching
    - linux

  tasks:
    - name: P-6_T-1 Run safe 'apt upgrade' for Debian/Ubuntu systems
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Update apt cache if older than 1 hour
        upgrade: safe # The 'safe' upgrade option only upgrades what can be upgraded without installing new packages
      when: ansible_os_family == 'Debian'
      tags:
        - patching
        - linux

    - name: P-6_T-2 Run safe 'dnf/yum/zypper update' for RHEL/SUSE systems
      ansible.builtin.package:
        name: '*'
        state: latest
      # This task works correctly for RedHat and Suse families to only update installed packages
      when: ansible_os_family in ['RedHat', 'Suse']
      tags:
        - patching
        - linux


- name: P-7 Perform a full distribution upgrade (dist-upgrade)
  hosts: all
  become: yes # Needed for package management
  gather_facts: yes # Needed to use ansible_os_family
  tags:
    - dist-upgrade
    - linux
  tasks:
    - name: Run 'apt full-upgrade' (dist-upgrade) for Debian/Ubuntu systems
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Update apt cache if older than 1 hour
        upgrade: dist # or 'full' - they are synonyms
      when: ansible_os_family == 'Debian'

    - name: Run 'dnf/yum/zypper update' for RHEL/SUSE systems
      # For RPM-based systems, 'state: latest' with name: '*' performs a full update
      ansible.builtin.package:
        name: '*'
        state: latest
      when: ansible_os_family in ['RedHat', 'Suse']

    - name: Check if reboot is required (common after dist-upgrades, e.g. kernel updates)
      ansible.builtin.command: needs-restarting -r
      register: reboot_check_result
      ignore_errors: true # The command exits with error code 1 if a reboot is needed
      changed_when: reboot_check_result.rc == 1
      when: ansible_os_family in ['RedHat', 'Suse']

    - name: Perform a system reboot if necessary
      ansible.builtin.reboot:
      # Use the reboot-required file created by apt or the command result from dnf check
      when:
        - ansible_os_family == 'Debian' and ansible_facts['system']['lsb']['release'] == "reboot required" # Example apt check
        - ansible_os_family in ['RedHat', 'Suse'] and reboot_check_result.rc == 1


...