---
# VMware Specific Playbook
- name: VMWare controls for AAP Demo Environment
  #hosts: vmware_hosts
  hosts: all
  gather_facts: yes
  become: yes
  tags:
    - vmware
  vars:

  vars_files:
    - vars/vmware_vars.yml
    - vars/vault.yml
  
  tasks:
    - name: P1_T1 Revert VM to Snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        folder: "{{ vcenter_folder }}"
        name: "{{ inventory_hostname }}"
        snapshot_name: "{{ vm_snapshot_name }}"
        state: reverted
      delegate_to: localhost
      tags:
        - vmware



...